[package]
name = "hide-my-js"
version = "0.1.0"
edition = "2021"

[dependencies]
oxc = { version = "0.48.1", features = ["full"] }
rand = "0.9.0"
base64 = "0.22.1"

[dev-dependencies]
reqwest = { version = "0.12.12", features = ["blocking"] }
